name: sipn_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  awesome_dialog: ^3.1.0
  json_annotation: ^4.8.1
  dio: ^5.3.3
  intl: ^0.18.1
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  flutter_riverpod: ^2.4.0
  syncfusion_flutter_charts: ^27.2.4
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3 
  firebase_core: ^3.8.0
  firebase_core_web: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/company_logo.png
    - assets/images/app_logo.png