// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14_b_d72uigU7D8_bXZMR5IR-CQnMEsM',
    appId: '1:618926908230:web:4b25ddfeac1efc331abb47',
    messagingSenderId: '618926908230',
    projectId: 'siperring',
    authDomain: 'siperring.firebaseapp.com',
    storageBucket: 'siperring.firebasestorage.app',
    measurementId: 'G-JGQV51V9FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rfG_hg2Rmv3aN7mZvUiIKdMCtqcaZOc',
    appId: '1:618926908230:android:dd62a251eb122c561abb47',
    messagingSenderId: '618926908230',
    projectId: 'siperring',
    storageBucket: 'siperring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDhCD6IWUKbNCr1KtHfhIBe3cA1LignM',
    appId: '1:618926908230:ios:ea8f40eb7a3a34761abb47',
    messagingSenderId: '618926908230',
    projectId: 'siperring',
    storageBucket: 'siperring.firebasestorage.app',
    iosBundleId: 'com.example.sipnAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNDhCD6IWUKbNCr1KtHfhIBe3cA1LignM',
    appId: '1:618926908230:ios:ea8f40eb7a3a34761abb47',
    messagingSenderId: '618926908230',
    projectId: 'siperring',
    storageBucket: 'siperring.firebasestorage.app',
    iosBundleId: 'com.example.sipnAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14_b_d72uigU7D8_bXZMR5IR-CQnMEsM',
    appId: '1:618926908230:web:3fb001ffd26ff19d1abb47',
    messagingSenderId: '618926908230',
    projectId: 'siperring',
    authDomain: 'siperring.firebaseapp.com',
    storageBucket: 'siperring.firebasestorage.app',
    measurementId: 'G-G5QS109SW8',
  );
}
